name: Bug Report for API & Coding Agent
description: Report a bug related to API or Coding Agent tools to help us reproduce and fix the problem.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out! Please make sure to check the [GitHub README](https://github.com/MiniMax-AI) of the model and the [MiniMax Documentation](https://www.minimax.io/platform_overview). And please provide the details below to help us resolve it quickly.

  - type: input
    attributes:
      label: Basic Information - Models Used
      description: |
        Please list the model used, e.g., MiniMax-M2, speech-2.6-hd, etc.
        Our models can be referred at [HuggingFace](https://huggingface.co/MiniMaxAI) or [the official site](https://www.minimax.io/platform_overview).
      placeholder: "eg: MiniMax-M2"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Please **describe the bug** you have encountered when using the API or coding agent tools, and **paste the screenshots** of the error or unexpected behaviour here.
        The following template is recommended.
        Feel free to modify as you needed.
      value: |
        
        ## API type or Coding Agent Tool

        ## Steps to Reproduce
        1. ...
        2. ...



        ## Example Input or Query
        system: ...
        user: ...

        ## Error Logs / Trace ID
        ...

        ## Screenshots

    validations:
      required: true
